// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDsmPH5FtesQ7obPIQhqUfnzWcoozTNEk',
    appId: '1:353479550210:web:807cc63d56c094d35ece1b',
    messagingSenderId: '353479550210',
    projectId: 'memorando-jba',
    authDomain: 'memorando-jba.firebaseapp.com',
    storageBucket: 'memorando-jba.firebasestorage.app',
    measurementId: 'G-6SV9Z12E32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV4wQJu-DBUHzJea1hvQHeEo2aHvbeVfo',
    appId: '1:353479550210:android:f46791fb08fc34045ece1b',
    messagingSenderId: '353479550210',
    projectId: 'memorando-jba',
    storageBucket: 'memorando-jba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbVHof8tSLLl9DpWPVEE0-9eNAMsr5Tzs',
    appId: '1:353479550210:ios:8798b200dd3ce3735ece1b',
    messagingSenderId: '353479550210',
    projectId: 'memorando-jba',
    storageBucket: 'memorando-jba.firebasestorage.app',
    iosBundleId: 'com.example.memorando',
  );
}
